#  Binning factor to get downsampled images. This factor will be applied
#  to the image width as well as the image height
# binning: 1

# The tf frame under which the images were published
camera_frame: pylon_camera

# The DeviceUserID of the camera. If empty, the first camera found in the
# device list will be used
device_user_id: ""

##########################################################################
######################## Image Intensity Settings ########################
##########################################################################
# The following settings do *NOT* have to be set. Each camera has default
# values which provide an automatic image adjustment
# If one would like to adjust image brightness, it is not
##########################################################################

#  The exposure time in microseconds after opening the camera.
#  This value can be overriden from the brightness search, in case that
#  the flag exposure_fixed is not true
# exposure: 10000.0

#  If the exposure_fixed flag is set, the exposure time will stay fix in
#  case of a brightness search. Hence the target brightness will be reached
#  only by varying the gain
# exposure_fixed: false

#  The average intensity value of the image. It depends the exposure time
#  as well as the gain setting. The interface will only try to reach this
#  value if the brightness_enabled flag is set to true.
# brightness: 100

#  The brightness_continuous flag controls the auto brightness function.
#  If it is set to false, the given brightness will only be reached once.
#  Hence changing light conditions lead to changing brightness values.
#  If it is set to true, the given brightness will be reached continuously,
#  trying to adapt to changing light conditions
# brightness_continuous: true

#  The target gain in percent of the maximal value the camera supports
#  For USB-Cameras, the gain is in dB, for GigE-Cameras it is given in so
#  called 'device specific units'. This value can be overriden from the
#  brightness search, in case that the gain_fixed flag is set to false
# gain: 0.5

#  If the gain_fixed flag is set, the gain value will stay fix in
#  case of a brightness search. Hence the target brightness will be reached
#  only by varying the exposure
# gain_fixed: true

#  Gamma correction of pixel intensity.
#  Adjusts the brightness of the pixel values output by the camera's sensor
#  to account for a non-linearity in the human perception of brightness or
#  of the display system (such as CRT).
# gamma: 1.0
##########################################################################

#  The desired publisher frame rate if listening to the topics.
#  This paramter can only be set once at startup
#  Calling the GrabImages-Action can result in a higher framerate
frame_rate: 10.0

#  The MTU size. Only used for GigE cameras.
#  To prevent lost frames configure the camera has to be configured
#  with the MTU size the network card supports. A value greater 3000
#  should be good (1500 for RaspberryPI)
# gige:
#  mtu_size: 3000
